# Generated by Django 3.1.1 on 2021-06-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.IntegerField(verbose_name='Clinic ID')),
                ('physician', models.IntegerField(verbose_name='Physician ID')),
                ('patient', models.IntegerField(verbose_name='Patient ID')),
                ('text', models.TextField(verbose_name='Text')),
            ],
        ),
    ]
