"""
Django settings for project_prescription project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qls_$a0!$=hyu%m3sm=o(u8io7@uqe78u_p(=_cau8(_5tx&2b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'prescription',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project_prescription.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_prescription.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": config('POSTGRES_DB', cast=str),
        "USER": config('POSTGRES_USER', cast=str),
        "PASSWORD": config('POSTGRES_PASSWORD', cast=str),
        "HOST": config('POSTGRES_HOST', cast=str),
        "PORT": config('POSTGRES_PORT', cast=int),
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

ERROR_REST = (
    ('01', 'malformed request'),
    ('02', 'physician not found'),
    ('03', 'patient not found'),
    ('04', 'metrics service not available'),
    ('05', 'physicians service not available'),
    ('06', 'patients service not available'),
)

TRIES = (
    ('CLINICS', 3),
    ('PHYSICIANS', 2),
    ('PATIENTS', 2),
    ('METRICS', 5),
)

TOKENS_BEARER = (
    ('CLINICS', config('CLINICS_BEARER', cast=str)),
    ('PHYSICIANS', config('PHYSICIANS_BEARER', cast=str)),
    ('PATIENTS', config('PATIENTS_BEARER', cast=str)),
    ('METRICS', config('METRICS_BEARER', cast=str)),
)

HOST_DEPENDENTS = (
    ('CLINICS', config('CLINICS_HOST', cast=str)),
    ('PHYSICIANS', config('PHYSICIANS_HOST', cast=str)),
    ('PATIENTS', config('PATIENTS_HOST', cast=str)),
    ('METRICS', config('METRICS_HOST', cast=str)),
)

TIMEOUT_DEPENDENTS = (
    ('CLINICS', 5),
    ('PHYSICIANS', 4),
    ('PATIENTS', 3),
    ('METRICS', 6),
)

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
