version: '3.3'
services:
    postgres:
        image: postgres:12-alpine
        env_file:
            - /mnt/d/iclinic/envs/PostgresSql.env
        
    prescription:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
        - /d/iclinic/source:/source
        env_file:
            - /mnt/d/iclinic/envs/PostgresSql.env
            - /mnt/d/iclinic/envs/.env
        ports:
            - 8000:8000
        depends_on:
            - postgres
    